config/routes.rb
Songsineed::Application.routes.draw do
  
  get 'songs/toggle_found'
  
  resources :genres

  resources :songs
  root :to => 'songs#index'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_and_belongs_to_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_and_belongs_to_many :genres
  validates_uniqueness_of :title
  
  def self.search(search)
    if search
      where( 'LOWER(title) LIKE ? OR LOWER(artist) LIKE ? or LOWER(album) LIKE ?', "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%" )
    else
      scoped
    end
  end
end

# == Schema Information
#
# Table name: songs
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  artist     :string(255)
#  album      :string(255)
#  genre      :string(255)
#  created_at :datetime
#  updated_at :datetime
#  notes      :text
#  found      :boolean         default(FALSE)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  # GET /genres
  # GET /genres.xml
  def index
    @genres = Genre.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @genres }
    end
  end

  # GET /genres/1
  # GET /genres/1.xml
  def show
    @genre = Genre.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @genre }
    end
  end

  # GET /genres/new
  # GET /genres/new.xml
  def new
    @genre = Genre.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @genre }
    end
  end

  # GET /genres/1/edit
  def edit
    @genre = Genre.find(params[:id])
  end

  # POST /genres
  # POST /genres.xml
  def create
    @genre = Genre.new(params[:genre])

    respond_to do |format|
      if @genre.save
        format.html { redirect_to(@genre, :notice => 'Genre was successfully created.') }
        format.xml  { render :xml => @genre, :status => :created, :location => @genre }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @genre.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /genres/1
  # PUT /genres/1.xml
  def update
    @genre = Genre.find(params[:id])

    respond_to do |format|
      if @genre.update_attributes(params[:genre])
        format.html { redirect_to(@genre, :notice => 'Genre was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @genre.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.xml
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to(genres_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  helper_method :sort_column, :sort_direction
  
  
  # GET /songs/toggle_found.json
  def toggle_found
    @song = Song.find(params[:id])
    @song.found = !@song.found
    @song.save
    render :nothing => true
  end
  
  # GET /songs
  def index
    @songs = Song.search(params[:search]).order("found asc, " + sort_column + " " + sort_direction).paginate(:per_page => 20, :page => params[:page])
    
    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
      format.xml  { render :xml => @genres }
    end
    
  end

  # GET /songs/1
  # GET /songs/1.xml
  def show
    @song = Song.find(params[:id])

  end

  # GET /songs/new
  # GET /songs/new.xml
  def new
    @song = Song.new
    @genres = Genre.order("name ASC")
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
    @genres = Genre.order("name ASC")
  end

  # POST /songs
  # POST /songs.xml
  def create
    @song = Song.new(params[:song])
    respond_to do |format|
      if @song.save
        format.html { redirect_to(@song, :notice => 'Song was successfully created.') }
        format.xml  { render :xml => @song, :status => :created, :location => @song }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.xml
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to(@song, :notice => 'Song was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.xml
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to(songs_url) }
      format.xml  { head :ok }
    end
  end
  
  
  private
  
  def sort_column
    Song.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" :nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<h1>Listing genres</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @genres.each do |genre| %>
  <tr>
    <td><%= genre.name %></td>
    <td><%= link_to 'Show', genre %></td>
    <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
    <td><%= link_to 'Destroy', genre, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Genre', new_genre_path %>

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @genre.name %>
</p>


<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Songsineed</title>
  <link rel="stylesheet" href="/stylesheets/blueprint/screen.css" type="text/css" media="screen, projection">
  <link rel="stylesheet" href="/stylesheets/blueprint/print.css" type="text/css" media="print">	
  <!--[if lt IE 8]><link rel="stylesheet" href="/stylesheets/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery', 'rails', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :album %><br />
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
	<% @genres.each do |genre| %>
		<%= check_box_tag 'song[genre_ids][]', genre.id, @song.genre_ids.include?(genre.id) %><%= genre.name.humanize %>
	<% end %>
  </div>
  <div class="field">
 	<%= f.check_box(:found, {}, true, false) %> Found?
  </div>
  <div class="field">
	<%= f.label :notes %><br />
	<%= f.text_area(:notes, {:rows=>2, :cols=>30})%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_songs.html.erb
<table class="pretty">
  <thead>
  <tr>
    <th><%= sortable "title" %></th>
    <th><%= sortable "artist" %></th>
    <th><%= sortable "album" %></th>
    <th>Genres</th>
	<th><%= sortable "created_at", "Added" %></th>
	<th>Found?</th>
	<th>Notes</th>
    <!--<th></th>-->
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @songs.each do |song| %>
  <tr>
    <td><%= song.title %></td>
    <td><%= song.artist %></td>
    <td><%= song.album %></td>
    <td><%= song.genres.collect(&:name).to_sentence %></td>
	<td><%= song.created_at.strftime("%D") %></td>
	<td><input type="checkbox" class="song_found" data-id="<%= song.id %>" <%= (song.found) ? "checked" : "" %>></td>
	<td><%= song.notes %></td>
    <!--<td><%= link_to 'Show', song %></td>-->
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Destroy', song, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
  </tbody>
</table>

<%= will_paginate @songs %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Songs I Need</h1>
<%= form_tag songs_path, :method => 'get', :id => "songs_search" do %>
		<%= hidden_field_tag :direction, params[:direction] %>
		<%= hidden_field_tag :sort, params[:sort] %>
		
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil %>
<% end %>

<div id="songs"><%= render "songs" %></div>

<br/>
<%= link_to 'add new song', new_song_path %>

<script type="text/javascript">
	$('.song_found').click(function(){
		var id = $(this).attr('data-id')
		//alert(id);
		$.get(
			'/songs/toggle_found.json',
			{
				id : id
			}
		)
	})
</script>

app/views/songs/index.js.erb
$("#songs").html( "<%= escape_javascript( render( "songs" ) ) %>" )

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @song.title %>
</p>

<p>
  <b>Artist:</b>
  <%= @song.artist %>
</p>

<p>
  <b>Album:</b>
  <%= @song.album %>
</p>

<p>
  <b>Genre:</b>
  <%= @song.genres.collect(&:name).to_sentence %>
</p>

<p>
  <b>Added:</b>
  <%= @song.created_at.strftime("%D") %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>
<br/><br/>
<%= link_to 'add new song', new_song_path %>